"""
app/models/notification.py
──────────────────────────────────────────────────────────────────────────────
Notification model — in-app notifications for users.

Notifications are generated by the system when important events occur:
  - Donor gets notified when a recipient claims their listing
  - Recipient gets notified when their verification is approved/rejected
  - Both parties get notified on claim status changes
  - Everyone gets expiry warnings for their listings

TABLE: notifications
"""

import uuid
from datetime import datetime
from typing import Optional
from sqlalchemy import String, Boolean, DateTime, Text, Enum as SAEnum, func, ForeignKey, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID

from app.db.base import Base
from app.utils.enums import NotificationType


class Notification(Base):
    __tablename__ = "notifications"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )

    # ── Foreign Keys ──────────────────────────────────────────────────────────
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Optional: link to the related listing (for navigation in frontend)
    listing_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("listings.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Optional: link to the related claim
    claim_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("claims.id", ondelete="SET NULL"),
        nullable=True,
    )

    # ── Notification Content ──────────────────────────────────────────────────
    type: Mapped[NotificationType] = mapped_column(
        SAEnum(NotificationType, name="notificationtype", create_type=True),
        nullable=False,
        index=True,
    )

    title: Mapped[str] = mapped_column(String(300), nullable=False)

    message: Mapped[str] = mapped_column(Text, nullable=False)

    # Frontend navigation link (e.g., "/donor/claims")
    link: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # ── Read Status ───────────────────────────────────────────────────────────
    read: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    user: Mapped["User"] = relationship("User", foreign_keys=[user_id])
    listing: Mapped[Optional["Listing"]] = relationship(
        "Listing", back_populates="notifications", foreign_keys=[listing_id]
    )
    claim: Mapped[Optional["Claim"]] = relationship(
        "Claim", back_populates="notifications", foreign_keys=[claim_id]
    )

    __table_args__ = (
        Index("ix_notifications_user_read", "user_id", "read"),
        Index("ix_notifications_user_created", "user_id", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<Notification id={self.id} type={self.type} user_id={self.user_id} read={self.read}>"
